// generated by rapydscript from the python file

"use strict";

function rs_with__name__(fn, name) {
    fn.__name__ = name;
    return fn;
}

function rs_Iterable(iterable) {
    var tmp;
    if (iterable.constructor === [].constructor || iterable.constructor === "".constructor || (tmp = Array.prototype.slice.call(iterable)).length) {
        return tmp || iterable;
    }
    if (Set && iterable.constructor === Set) {
        return Array.from(iterable);
    }
    return Object.keys(iterable);
}

(function () {

    var __name__ = "__main__";

    document.getElementById("result").innerHTML = "Compiled Python script in Chrome";
    console.log("hello from python");
})();
